<?php
$SMM_VERSION="2.0";
$INSTALL_DIR="/data/7DTD";
@$STEAMCMD_NO_VALIDATE=$_ENV['STEAMCMD_NO_VALIDATE'];
@$STEAMCMD_BETA=$_ENV['STEAMCMD_BETA'];
@$STEAMCMD_BETA_PASSWORD=$_ENV['STEAMCMD_BETA_PASSWORD'];
?>
